import { SIHDemoScenario, LocationData } from "@/types/weather";

export const SIH_DEMO_SCENARIOS: SIHDemoScenario[] = [
  {
    id: "scenario-1",
    scenarioNumber: 1,
    title: "Approaching Severe Monsoon & Cyclone Alert",
    subtitle: "Heavy downpours, gale gusts, and waterlogging advisory in Western India",
    location: {
      id: "ahmedabad",
      name: "Ahmedabad",
      admin1: "Gujarat",
      country: "India",
      latitude: 23.0225,
      longitude: 72.5714,
      timezone: "Asia/Kolkata",
    },
    queryPrompt: "Will there be heavy rain and storm alerts in Ahmedabad tonight and tomorrow?",
    contextDescription: "Demonstrates severe weather warning detection, rainfall intensity charts, emergency preparedness checklists, and real-time radar tracking.",
    simulatedWeatherState: "heavy_monsoon",
    tag: "🚨 Severe Alerts & Flooding",
  },
  {
    id: "scenario-2",
    scenarioNumber: 2,
    title: "45°C Extreme Heatwave & High UV Advisory",
    subtitle: "Thermal stress risk, hydration plans, and solar radiation warnings",
    location: {
      id: "delhi",
      name: "New Delhi",
      admin1: "Delhi",
      country: "India",
      latitude: 28.6139,
      longitude: 77.209,
      timezone: "Asia/Kolkata",
    },
    queryPrompt: "How severe is the heatwave in Delhi today, and what precautions are advised?",
    contextDescription: "Demonstrates thermal stress calculation, UV radiation index alerts, and actionable lifestyle / work shift recommendations.",
    simulatedWeatherState: "heatwave",
    tag: "🔥 Heatwave & UV Index",
  },
  {
    id: "scenario-3",
    scenarioNumber: 3,
    title: "Outdoor Cricket Match Feasibility at 5 PM",
    subtitle: "Match playability index, precipitation window, and alternative schedule recommendation",
    location: {
      id: "ahmedabad",
      name: "Ahmedabad",
      admin1: "Gujarat",
      country: "India",
      latitude: 23.0225,
      longitude: 72.5714,
      timezone: "Asia/Kolkata",
    },
    queryPrompt: "I have a cricket match tomorrow at 5 PM in Ahmedabad. Should we play?",
    contextDescription: "Demonstrates domain-specific AI intelligence (cricket, outfield dampness, rain probabilities, lighting) with a clear risk score and backup time slot.",
    simulatedWeatherState: "cricket_evening",
    tag: "🏏 Sports & Cricket AI",
  },
  {
    id: "scenario-4",
    scenarioNumber: 4,
    title: "Mountain Highway Travel & Landslide Risk Advisor",
    subtitle: "High-altitude road conditions, fog visibility, and travel safety rating",
    location: {
      id: "manali",
      name: "Manali",
      admin1: "Himachal Pradesh",
      country: "India",
      latitude: 32.2432,
      longitude: 77.1892,
      timezone: "Asia/Kolkata",
    },
    queryPrompt: "Is it safe to drive to Manali this weekend considering mountain weather and rain?",
    contextDescription: "Demonstrates travel risk matrices, reduced visibility warnings, high altitude precipitation trends, and transit checklists.",
    simulatedWeatherState: "mountain_travel",
    tag: "✈️ Travel & Road Safety",
  },
  {
    id: "scenario-5",
    scenarioNumber: 5,
    title: "Dual-City Climate Shift Comparison",
    subtitle: "15-year historical warming, monsoon anomalies, and side-by-side comparison",
    location: {
      id: "ahmedabad",
      name: "Ahmedabad",
      admin1: "Gujarat",
      country: "India",
      latitude: 23.0225,
      longitude: 72.5714,
      timezone: "Asia/Kolkata",
    },
    queryPrompt: "Compare the weather and long-term climate shift between Ahmedabad and Mumbai.",
    contextDescription: "Demonstrates dual-city comparison engine with historical decadal temperature warming, AQI comparison, and precipitation shifts.",
    simulatedWeatherState: "dual_city_climate",
    tag: "🌍 Climate Intelligence",
  },
];
